export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const SET_SEARCH_DATA = 'SET_SEARCH_DATA';
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_REPOS_DATA = 'SET_REPOS_DATA';
export const SET_REPO_DETAILS = 'SET_REPO_DETAILS';
